### ISSUE TITLE
Require description string for !pay and !deduct commands

### ISSUE THREAD

**Issue by vanessasickles** [Monbrey/ultra-rpg-bot#25]
!pay @Monbrey 5000 [desc]

I'd honestly require the description, since we want to know why people would be manually paying/deducting.

**Comment by Monbrey** [comment]
#3

**Comment by Monbrey** [comment]
Flagging this as todo, will be done before release. !reflog and !judgelog now support this, these two commands will be next

**Comment by Monbrey** [comment]
This is now done - !pay and !deduct both now use the name args parser which automatically concatenates any remaining arguments into the last named parameter
